# Generated by Django 4.1.7 on 2023-03-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1000)),
                ('emailtype', models.CharField(blank=True, choices=[('Promotional', 'Promotional'), ('Store News', 'Store News'), ('Seasonal Sales', 'Seasonal Sales')], max_length=50, null=True)),
                ('product1_image', models.ImageField(blank=True, default=None, null=True, upload_to='email_imageAttachment/')),
                ('product1_name', models.CharField(blank=True, max_length=60, null=True)),
                ('product1_description', models.CharField(blank=True, max_length=200, null=True)),
                ('product1_link', models.URLField(blank=True, max_length=100, null=True)),
                ('product2_image', models.ImageField(blank=True, default=None, null=True, upload_to='email_imageAttachment/')),
                ('product2_name', models.CharField(blank=True, max_length=60, null=True)),
                ('product2_description', models.CharField(blank=True, max_length=200, null=True)),
                ('product2_link', models.URLField(blank=True, max_length=100, null=True)),
                ('product3_image', models.ImageField(blank=True, default=None, null=True, upload_to='email_imageAttachment/')),
                ('product3_name', models.CharField(blank=True, max_length=60, null=True)),
                ('product3_description', models.CharField(blank=True, max_length=200, null=True)),
                ('product3_link', models.URLField(blank=True, max_length=100, null=True)),
                ('product4_image', models.ImageField(blank=True, default=None, null=True, upload_to='email_imageAttachment/')),
                ('product4_name', models.CharField(blank=True, max_length=60, null=True)),
                ('product4_description', models.CharField(blank=True, max_length=200, null=True)),
                ('product4_link', models.URLField(blank=True, max_length=100, null=True)),
                ('subscribe_to_newsletter', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
