# Generated by Django 4.1.7 on 2023-03-11 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_emailApp', '0003_emailtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtask',
            old_name='email',
            new_name='emailToSend',
        ),
    ]
