# Generated by Django 4.1.7 on 2023-03-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_emailApp', '0004_rename_email_emailtask_emailtosend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtask',
            name='priority',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emailtask',
            name='task_description',
            field=models.TextField(max_length=200),
        ),
    ]
