# Generated by Django 4.1.7 on 2023-03-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_emailApp', '0005_alter_emailtask_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyJobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('job_id', models.CharField(max_length=255)),
                ('decription', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
