# Generated by Django 4.1.7 on 2023-03-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_emailApp', '0006_emailtask_job_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=200)),
                ('job_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='emailtask',
            name='job_id',
        ),
    ]
