# Generated by Django 4.1.7 on 2023-03-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_emailApp', '0007_scheduledjob_remove_emailtask_job_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduledJob',
            new_name='CustomScheduledJob',
        ),
    ]
