# Generated by Django 4.1.7 on 2023-03-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_emailApp', '0008_alter_emailtask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtask',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
