# Generated by Django 4.1.7 on 2023-03-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_emailApp', '0009_emails_updated_at_emailtask_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='myjobmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='myjobmodel',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
