# Generated by Django 4.1.7 on 2023-03-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_emailApp', '0010_customscheduledjob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomScheduledJob',
        ),
    ]
