# Generated by Django 4.1.7 on 2023-03-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_emailApp', '0010_myjobmodel_created_at_myjobmodel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='emailtype',
            field=models.CharField(choices=[('Promotional', 'Promotional'), ('Store News', 'Store News'), ('Seasonal Sales', 'Seasonal Sales')], max_length=50, null=True),
        ),
    ]
