# Generated by Django 4.1.7 on 2023-03-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_emailApp', '0011_alter_emails_emailtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('name', 'subject', 'url')},
            },
        ),
    ]
