# Generated by Django 4.1.7 on 2023-03-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_emailApp', '0011_delete_customscheduledjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=200)),
                ('job_id', models.CharField(max_length=200)),
            ],
        ),
    ]
