# Generated by Django 4.1.7 on 2023-03-13 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_formApp', '0002_user_welcome_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDjangoJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobstore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_formApp.customdjangojob')),
            ],
        ),
    ]
